<a href="https://colab.research.google.com/github/chrisdrake112/R-Python/blob/main/JoinPython.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [42]:
import pandas as pd

In [44]:
NHS = pd.read_excel('/content/HSE Report.xlsx')

In [45]:
AccountNum = pd.read_excel('/content/accountNumbers.xlsx')

In [46]:
NHS.head()

,Patient,Model of Device,Serial Number,Pediatric,Adult,Child Bearing Age,Date End User Notified,Patient Status,Contract Type,Replacement Date,Replacement Model,Replacement Device,Replaced/Repaired,Hospital,Comment
0,I0000126,CPAP_Dreamstation Auto CPAP GBX500S15,J2145398291AE,No,Yes,NO,NaN,Unresolved,CPAP,NaN,NaN,NaN,NaN,ALTNAGELVIN AREA HOSPITAL,NaN
1,I0000164,CPAP_REMSTAR AUTO___RI_A,M000935494,No,Yes,NO,NaN,Resolved,CPAP,2022-03-08,CPAP_Dreamstation Auto CPAP GBX500S15,J323375961785,Repaired,NaN,NaN
2,I0000165,CPAP_REMSTAR PLUS_M SERIES__RI_A,M000935485,No,Yes,NO,NaN,Unresolved,CPAP,NaN,NaN,NaN,NaN,NaN,NaN
3,I0000168,CPAP_Dreamstation Auto CPAP GBX500S15,J21773694BD72,No,No,NO,NaN,Resolved,CPAP,2022-11-03,CPAP_Dreamstation Auto CPAP GBX500S15,J2234092859B2,Repaired,ALTNAGELVIN AREA HOSPITAL,NaN
4,I0000184,CPAP_Dreamstation Auto CPAP GBX500S15,J23169275AD21,No,Yes,NO,NaN,Resolved,CPAP,2022-09-06,CPAP_Dreamstation Auto CPAP GBX500S15,J3341343123F6,Repaired,ALTNAGELVIN AREA HOSPITAL,NaN

In [14]:
AccountNum.head()

,Account Number,Date Of Birth,Address Line 2,Address Line 3,Address Line 4,Address Line 5
0,I0001650,1947-04-11,3 DRUIDS COURT,DRUIDS GLEN GOLF RESORT,NaN,A63 KX70
1,I0003453,2011-06-03,NaN,NaN,NaN,A82 AY63
2,I0003106,1964-04-14,23 ST OLIVER PLUNKETT,KENTSTOWN,NaN,A91 H5C2
3,I0004461,1957-12-26,NaN,NaN,NaN,H12 HX47
4,I0007043,1921-01-01,NaN,Donegal,NaN,F94 V6P3

In [47]:
NHSAccountNum = pd.merge(NHS,AccountNum,
                  how = 'left',
                  left_on='Patient',
                  right_on='Account Number')

In [48]:
len(NHSAccountNum)

5201

In [50]:
NHSAccountNum.to_excel('NHSAccountNum.xlsx',index = False)